"""
Recipe Import and Automatic Elaboration Management Module.

This module provides the management command `import_recipe` and underlying services
to scrape, analyze, summarize, and persist recipes from diverse sources (Web URLs,
YouTube videos, and local documents) into the database, generating structured `Recipes`,
`RecipesLinks`, associated `Files`, category associations, and automatic `Elaborations`
with ingredient mentions and preparation instructions using a local Ollama LLM instance.

========================================================================================
KEY FUNCTIONALITIES & ARCHITECTURE:
========================================================================================

1. Multi-Source Recipe Ingestion:
   - Web URLs (`--url`): Scrapes web pages, extracts semantic recipe text, titles,
     and meta descriptions while filtering out scripts, navigation, and boilerplate.
   - YouTube URLs:
     * Downloads highest-resolution video snapshot/thumbnail and saves it to `Files`,
       linking it as the Recipe's 'Main Photo' (`RecipesLinks`).
     * Extracts spoken subtitles and auto-generated captions (WebVTT) via `yt-dlp`.
     * Extracts and converts audio track to MP3 via `yt-dlp` for multimodal LLM processing.
     * Extracts video title, description, and metadata.
   - Local Documents (`--document` / `--file`): Extracts text from plain text, Markdown,
     HTML, JSON, and PDF files, attaching the original file to `Files` and `RecipesLinks`.
   - Existing Recipe Elaboration (`--from-recipe-id`): Generates an automatic elaboration
     for an already persisted `Recipes` record using all its linked sources.

2. Local LLM (Ollama) Integration & Resilient Parsing:
   - Integrates with local Ollama instances (`OllamaClient`, default model `gemma4:e2b`).
   - Supports multimodal audio and text prompts for precise culinary extraction.
   - Resilient Multi-Layer JSON Parser:
     * Supports `strict=False` parsing for unescaped control chars and newlines in strings.
     * Automatically cleans trailing commas in arrays and objects (`[...,]`, `{...,}`).
     * Auto-repairs unescaped backslashes and quotes.
     * Automatically balances and completes truncated JSON strings and containers.
     * Fallback regex parser to salvage structured recipe attributes if JSON decoding fails.
   - Internationalization (`--locale`, default `'es'`):
     * Dynamically prompts Ollama in the requested language (Spanish, English, etc.).
     * Localizes AI notices (e.g. `(Generado por IA)` / `(Generated by AI)`).

3. Database Persistence & Transactional Atomicity:
   - Full transactional safety (`@transaction.atomic`): All operations (Recipe creation,
     file uploads, link creations, category links, elaborations, ingredients, and text)
     are performed within atomic database transactions with complete rollback on error.
   - Strict Category Association: Associates recipes only with existing `RecipesCategories`
     found in the database, preventing the creation of unverified or orphan categories.
   - Elaborations & Rich Ingredient Spans: Enriches preparation steps (`ElaborationsTexts`)
     with HTML ingredient mention spans (`ElaborationsTexts.span_ingredient`).

4. High-Confidence Heuristic Product Matching (`ProductMatcher`):
   - Strict User Isolation: Matches ingredients ONLY against active, non-obsolete products
     owned by the target user (`Products.user == target_user`).
   - Normalization & Diacritic Stripping: Lowercases and strips accents/diacritics,
     punctuation, and redundant whitespace.
   - Morphological Normalization: Singularization and stemming (e.g. 'Huevos' -> 'Huevo').
   - Stopwords Filtering: Strips culinary filler words ('de', 'fresco', 'picado', 'crudo', etc.).
   - Conflicting Modifier Protection: Rejects matches containing mutually exclusive modifiers
     (e.g., olive oil vs sunflower oil, white wine vs red wine, whole milk vs skim milk).
   - High Confidence Threshold (>= 85%): Eliminates loose substring false positives
     (e.g., 'Sal' vs 'Salmón', 'Ajo' vs 'Majo').
   - Omission of Unmatched Items: Never inserts blank or placeholder product records.

5. CLI Options & Management Command:
   - `--url <URL>`: Scrapes and imports recipe from web page or YouTube video.
   - `--document <PATH>` / `--file <PATH>`: Imports recipe from a local document.
   - `--locale <CODE>`: Locale/language code (default: 'es').
   - `--user_id <ID>`: ID of the user who will own the recipe and whose products are matched.
   - `--username <NAME>`: Username of the user who will own the recipe.
   - `--from-recipe-id <ID>`: Generates automatic elaboration for an existing recipe ID.
   - `--no-elaboration`: Imports Recipe, Links, Categories, and Files without creating Elaborations.
"""

from decimal import Decimal
import base64
import difflib
from glob import glob
import html
import json
import logging
import mimetypes
import os
from os import path
import re
import shutil
import subprocess
import unicodedata
import urllib.error
import urllib.parse
import urllib.request

from django.conf import settings
from django.contrib.auth.models import User
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone, translation
from django.utils.translation import gettext as _

from calories_tracker import models

logger = logging.getLogger(__name__)


class OllamaClient:
    """
    Client for interacting with local Ollama API.
    """

    def __init__(self, base_url: str = None, model: str = None):
        """
        Initialize the Ollama client with base URL and model name.

        :param base_url: Ollama server URL (defaults to settings.OLLAMA_BASE_URL)
        :param model: Model identifier (defaults to settings.OLLAMA_MODEL)
        """
        self.base_url = (base_url or getattr(settings, "OLLAMA_BASE_URL", "http://localhost:11434")).rstrip("/")
        self.model = model or getattr(settings, "OLLAMA_MODEL", "gemma4:e2b")

    def generate(
        self,
        prompt: str,
        system_prompt: str = None,
        format_json: bool = True,
        audio_base64: str = None,
    ) -> dict | str:
        """
        Send a generation request to the Ollama server.

        :param prompt: User prompt to send to the model.
        :param system_prompt: Optional system prompt to guide LLM behavior.
        :param format_json: If True, request JSON response format from Ollama.
        :param audio_base64: Optional base64 encoded audio track to send to Ollama.
        :return: Parsed JSON dict if format_json is True, otherwise response string.
        :raises RuntimeError: On network error or Ollama execution failure.
        """
        endpoint = f"{self.base_url}/api/generate"
        payload = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": 0.1,
                "num_predict": 4096,
            },
        }
        if system_prompt:
            payload["system"] = system_prompt
        if format_json:
            payload["format"] = "json"
        if audio_base64:
            payload["audio"] = [audio_base64]
            payload["images"] = [audio_base64]

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            endpoint,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=180) as response:
                res_body = response.read().decode("utf-8")
                res_json = json.loads(res_body)
                raw_response = res_json.get("response", "")
        except urllib.error.URLError as e:
            raise RuntimeError(
                f"Error connecting to Ollama at {endpoint}. Ensure Ollama is running and model '{self.model}' is available. Error: {e}"
            ) from e
        except Exception as e:
            raise RuntimeError(f"Unexpected error communicating with Ollama: {e}") from e

        if format_json:
            return self._parse_json_response(raw_response)
        return raw_response

    @classmethod
    def _parse_json_response(cls, raw_text: str) -> dict:
        """
        Clean, repair, and parse a JSON response from the LLM, handling markdown codeblocks,
        unescaped newlines, trailing commas, missing delimiters, and truncated responses.

        :param raw_text: Raw string returned by LLM.
        :return: Parsed dictionary.
        """
        if not raw_text or not raw_text.strip():
            raise ValueError("Empty response received from LLM.")

        cleaned = raw_text.strip()

        # 1. Remove markdown fences if present
        match_codeblock = re.search(r"```(?:json)?\s*(.*?)\s*```", cleaned, re.DOTALL | re.IGNORECASE)
        if match_codeblock:
            cleaned = match_codeblock.group(1).strip()
        else:
            cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
            cleaned = re.sub(r"\s*```$", "", cleaned)
            cleaned = cleaned.strip()

        # 2. Extract substring between first '{' and last '}'
        first_brace = cleaned.find("{")
        last_brace = cleaned.rfind("}")
        if first_brace != -1 and last_brace != -1 and last_brace >= first_brace:
            json_candidate = cleaned[first_brace : last_brace + 1]
        else:
            json_candidate = cleaned

        # Attempt A: Direct loads with strict=False (allows unescaped control chars / literal newlines in strings)
        try:
            return json.loads(json_candidate, strict=False)
        except Exception:
            pass

        # Attempt B: Strip trailing commas before closing braces/brackets
        no_trailing = re.sub(r",\s*([\]}])", r"\1", json_candidate)
        try:
            return json.loads(no_trailing, strict=False)
        except Exception:
            pass

        # Attempt C: Clean and sanitize escape sequences
        repaired = cls._repair_json_string(no_trailing)
        try:
            return json.loads(repaired, strict=False)
        except Exception:
            pass

        # Attempt D: Auto-close incomplete/truncated JSON structures
        auto_closed = cls._auto_close_json(no_trailing)
        try:
            return json.loads(auto_closed, strict=False)
        except Exception:
            pass

        # Attempt E: Regex-based fallback extraction of recipe attributes
        fallback_data = cls._extract_fallback_recipe_data(raw_text)
        if fallback_data.get("name") and fallback_data.get("name") != "Receta sin título":
            logger.warning("Recovered structured recipe data via regex fallback parser.")
            return fallback_data

        # Final attempt: try parsing original cleaned with strict=False or return fallback
        try:
            return json.loads(cleaned, strict=False)
        except Exception as err:
            if fallback_data and fallback_data.get("name"):
                return fallback_data
            raise ValueError(f"Could not parse or repair JSON from LLM output: {err}. Raw output:\n{raw_text}") from err

    @staticmethod
    def _repair_json_string(text: str) -> str:
        """
        Repair common JSON formatting defects generated by LLMs.

        :param text: Candidate JSON string.
        :return: Sanitized string.
        """
        text = re.sub(r",\s*([\]}])", r"\1", text)
        text = re.sub(r'\\(?!["\\/bfnrtu])', r'\\\\', text)
        return text

    @staticmethod
    def _auto_close_json(text: str) -> str:
        """
        Attempt to complete a truncated JSON string by closing open strings, lists, and objects.

        :param text: Incomplete JSON candidate.
        :return: Completed JSON string.
        """
        text = text.strip()
        first_brace = text.find("{")
        if first_brace == -1:
            return text
        text = text[first_brace:]

        in_string = False
        escape = False
        stack = []

        for char in text:
            if escape:
                escape = False
                continue
            if char == "\\":
                escape = True
                continue
            if char == '"':
                in_string = not in_string
                continue
            if not in_string:
                if char in "{[":
                    stack.append(char)
                elif char == "}":
                    if stack and stack[-1] == "{":
                        stack.pop()
                elif char == "]":
                    if stack and stack[-1] == "[":
                        stack.pop()

        if in_string:
            text += '"'

        text = re.sub(r'[,:\s]+$', '', text)

        while stack:
            opener = stack.pop()
            if opener == "{":
                text += "}"
            elif opener == "[":
                text += "]"

        text = re.sub(r",\s*([\]}])", r"\1", text)
        return text

    @staticmethod
    def _extract_fallback_recipe_data(text: str) -> dict:
        """
        Extract recipe fields using regex when JSON parser cannot repair the string.

        :param text: Raw response text from LLM.
        :return: Dict with extracted recipe keys.
        """
        data = {
            "name": "Receta importada",
            "comment": "",
            "food_type": "Homemade food",
            "categories": [],
            "diners": 4,
            "ingredients": [],
            "steps": "",
        }

        # Name
        m_name = re.search(r'"name"\s*:\s*"((?:[^"\\]|\\.)*)"', text)
        if m_name:
            data["name"] = m_name.group(1).replace(r'\"', '"').strip()

        # Comment
        m_comm = re.search(r'"comment"\s*:\s*"((?:[^"\\]|\\.)*)"', text)
        if m_comm:
            data["comment"] = m_comm.group(1).replace(r'\"', '"').strip()

        # Food Type
        m_ft = re.search(r'"food_type"\s*:\s*"((?:[^"\\]|\\.)*)"', text)
        if m_ft:
            data["food_type"] = m_ft.group(1).replace(r'\"', '"').strip()

        # Diners
        m_din = re.search(r'"diners"\s*:\s*(\d+)', text)
        if m_din:
            try:
                data["diners"] = int(m_din.group(1))
            except ValueError:
                data["diners"] = 4

        # Steps
        m_steps = re.search(r'"steps"\s*:\s*"((?:[^"\\]|\\.)*)"', text, re.DOTALL)
        if m_steps:
            data["steps"] = m_steps.group(1).replace(r"\n", "\n").replace(r'\"', '"')
        else:
            m_steps_block = re.search(r'"steps"\s*:\s*([^,}]+)', text)
            if m_steps_block:
                data["steps"] = m_steps_block.group(1).strip().strip('"')

        # Categories
        m_cats = re.search(r'"categories"\s*:\s*\[(.*?)\]', text, re.DOTALL)
        if m_cats:
            cat_items = re.findall(r'"([^"]+)"', m_cats.group(1))
            data["categories"] = [c.strip() for c in cat_items if c.strip()]

        # Ingredients (match objects inside array)
        m_ings = re.search(r'"ingredients"\s*:\s*\[(.*?)\]\s*(?:,|\})', text, re.DOTALL)
        if m_ings:
            ing_blocks = re.findall(r'\{([^{}]+)\}', m_ings.group(1))
            for block in ing_blocks:
                ing_obj = {}
                name_m = re.search(r'"name"\s*:\s*"((?:[^"\\]|\\.)*)"', block)
                if name_m:
                    ing_obj["name"] = name_m.group(1).replace(r'\"', '"').strip()
                amt_m = re.search(r'"amount"\s*:\s*([0-9.]+)', block)
                if amt_m:
                    try:
                        ing_obj["amount"] = float(amt_m.group(1))
                    except ValueError:
                        ing_obj["amount"] = 100
                unit_m = re.search(r'"unit"\s*:\s*"((?:[^"\\]|\\.)*)"', block)
                if unit_m:
                    ing_obj["unit"] = unit_m.group(1).strip()
                comm_m = re.search(r'"comment"\s*:\s*"((?:[^"\\]|\\.)*)"', block)
                if comm_m:
                    ing_obj["comment"] = comm_m.group(1).replace(r'\"', '"').strip()
                if ing_obj.get("name"):
                    data["ingredients"].append(ing_obj)

        return data


class YouTubeHelper:
    """
    Helper for detecting YouTube URLs and fetching video thumbnail images.
    """

    YOUTUBE_REGEX = re.compile(
        r"(?:https?:\/\/)?(?:www\.|m\.)?(?:youtube\.com\/(?:watch\?v=|embed\/|v\/|shorts\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})"
    )

    @classmethod
    def get_video_id(cls, url: str) -> str | None:
        """
        Extract the 11-character YouTube video ID from a URL if present.

        :param url: URL string to inspect.
        :return: Video ID string or None.
        """
        if not url:
            return None
        match = cls.YOUTUBE_REGEX.search(url)
        return match.group(1) if match else None

    @classmethod
    def fetch_thumbnail(cls, video_id: str) -> tuple[bytes, str] | None:
        """
        Download the highest available resolution thumbnail image for a YouTube video.

        :param video_id: 11-character YouTube video ID.
        :return: Tuple (image_bytes, mime_type) or None if download fails.
        """
        print(f"[YouTube] Descargando snapshot/miniatura para el vídeo '{video_id}'...", flush=True)
        thumbnail_urls = [
            f"https://img.youtube.com/vi/{video_id}/maxresdefault.jpg",
            f"https://img.youtube.com/vi/{video_id}/hqdefault.jpg",
            f"https://img.youtube.com/vi/{video_id}/0.jpg",
        ]
        headers = {
            "User-Agent": (
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            )
        }
        for thumb_url in thumbnail_urls:
            try:
                req = urllib.request.Request(thumb_url, headers=headers)
                with urllib.request.urlopen(req, timeout=15) as resp:
                    if resp.status == 200:
                        content = resp.read()
                        # Some missing maxresdefault return 1097 byte placeholder; check valid length
                        if len(content) > 1500:
                            print(f"[YouTube] ✓ Snapshot descargado exitosamente ({len(content)} bytes, image/jpeg)", flush=True)
                            return content, "image/jpeg"
            except Exception as e:
                logger.debug("Failed downloading thumbnail from %s: %s", thumb_url, e)
        print(f"[YouTube] ⚠ No se pudo obtener snapshot/miniatura para '{video_id}'", flush=True)
        return None

    @classmethod
    def clean_vtt(cls, vtt_content: str) -> str:
        """
        Strip timing tags and formatting from WebVTT subtitles to get clean plain text.

        :param vtt_content: Raw VTT subtitle content.
        :return: Cleaned subtitle text.
        """
        lines = []
        for line in vtt_content.splitlines():
            line = line.strip()
            if (
                not line
                or line.startswith("WEBVTT")
                or line.startswith("Kind:")
                or line.startswith("Language:")
                or line.startswith("Style:")
                or line.startswith("NOTE")
                or line.startswith("REGION")
                or "-->" in line
                or line.isdigit()
            ):
                continue
            cleaned = re.sub(r"<[^>]+>", "", line).strip()
            if cleaned and (not lines or lines[-1] != cleaned):
                lines.append(cleaned)
        return " ".join(lines)

    @classmethod
    def extract_full_youtube_data(cls, url: str, video_id: str, locale: str = "es") -> dict:
        """
        Extract title, description, spoken subtitles/transcript, and audio track from YouTube using yt-dlp.

        :param url: YouTube video URL.
        :param video_id: 11-character YouTube video ID.
        :param locale: Preferred language code for subtitle extraction (default: "es").
        :return: Dict containing title, description, transcript, combined_text, and base64 audio.
        """
        result = {
            "title": "",
            "description": "",
            "transcript": "",
            "combined_text": "",
            "audio_base64": None,
        }

        ytdlp_bin = shutil.which("yt-dlp")
        tmp_dir = getattr(settings, "TMPDIR", "/tmp")

        if ytdlp_bin:
            # 1. Extract metadata and subtitles/transcripts
            print(f"[YouTube] Extrayendo metadatos y subtítulos con yt-dlp (ID: {video_id})...", flush=True)
            sub_template = f"{tmp_dir}/yt_sub_{video_id}"
            try:
                for f in glob(f"{sub_template}*"):
                    try:
                        os.remove(f)
                    except OSError:
                        pass

                clean_loc = (locale or "es").split("_")[0].lower()
                sub_langs = f"{clean_loc},{clean_loc}-orig,es,en,es-orig,en-orig,es-419"

                proc = subprocess.run(
                    [
                        ytdlp_bin,
                        "--dump-json",
                        "--skip-download",
                        "--write-auto-sub",
                        "--write-sub",
                        "--sub-lang", sub_langs,
                        "--sub-format", "vtt/best",
                        "-o", f"subtitle:{sub_template}",
                        url,
                    ],
                    capture_output=True,
                    text=True,
                    timeout=45,
                )
                if proc.returncode == 0 and proc.stdout:
                    try:
                        meta = json.loads(proc.stdout)
                        result["title"] = meta.get("title", "")
                        result["description"] = meta.get("description", "")
                        print(f"[YouTube] ✓ Título: '{result['title']}'", flush=True)
                    except Exception as e:
                        logger.debug("Failed parsing yt-dlp metadata JSON: %s", e)

                # Check for extracted subtitle files
                sub_files = glob(f"{sub_template}*.vtt")
                if sub_files:
                    try:
                        with open(sub_files[0], "r", encoding="utf-8", errors="replace") as sf:
                            result["transcript"] = cls.clean_vtt(sf.read())
                        print(f"[YouTube] ✓ Subtítulos extraídos ({len(result['transcript'])} caracteres)", flush=True)
                    except Exception as e:
                        logger.debug("Failed reading subtitle file: %s", e)
                    finally:
                        for f in sub_files:
                            try:
                                os.remove(f)
                            except OSError:
                                pass
                else:
                    print("[YouTube] ℹ No se encontraron subtítulos VTT; se usará la descripción", flush=True)
            except Exception as e:
                logger.debug("yt-dlp metadata/subtitle extraction error: %s", e)
                print(f"[YouTube] ⚠ Error extrayendo subtítulos: {e}", flush=True)

            # 2. Extract audio track from video
            print(f"[YouTube] Extrayendo y convirtiendo pista de audio a MP3 con yt-dlp (ID: {video_id})...", flush=True)
            audio_template = f"{tmp_dir}/yt_audio_{video_id}.%(ext)s"
            try:
                for f in glob(f"{tmp_dir}/yt_audio_{video_id}.*"):
                    try:
                        os.remove(f)
                    except OSError:
                        pass

                audio_proc = subprocess.run(
                    [
                        ytdlp_bin,
                        "-x",
                        "--audio-format", "mp3",
                        "--audio-quality", "5",
                        "-o", audio_template,
                        url,
                    ],
                    capture_output=True,
                    timeout=90,
                )
                if audio_proc.returncode == 0:
                    generated_audios = glob(f"{tmp_dir}/yt_audio_{video_id}.*")
                    if generated_audios:
                        with open(generated_audios[0], "rb") as af:
                            audio_bytes = af.read()
                            if audio_bytes:
                                result["audio_base64"] = base64.b64encode(audio_bytes).decode("utf-8")
                                print(f"[YouTube] ✓ Pista de audio convertida y codificada en Base64 ({len(audio_bytes)} bytes)", flush=True)
                        for af_path in generated_audios:
                            try:
                                os.remove(af_path)
                            except OSError:
                                pass
                else:
                    print(f"[YouTube] ⚠ Falló la conversión de audio: {audio_proc.stderr}", flush=True)
            except Exception as e:
                logger.debug("yt-dlp audio extraction error: %s", e)
                print(f"[YouTube] ⚠ Error al extraer pista de audio: {e}", flush=True)

        # Fallback to HTML extraction if title or description are empty
        if not result["title"] or not result["description"]:
            try:
                print("[YouTube] Realizando extracción fallback HTML...", flush=True)
                html_text, html_title = RecipeTextExtractor.extract_from_url(url)
                if not result["title"]:
                    result["title"] = html_title
                if not result["description"]:
                    result["description"] = html_text
            except Exception as e:
                logger.debug("HTML fallback error: %s", e)

        # Combine all gathered information into rich prompt context
        combined = f"Title: {result['title']}\n\nDescription:\n{result['description']}\n"
        if result["transcript"]:
            combined += f"\nVideo Transcript / Spoken Subtitles:\n{result['transcript']}\n"
        result["combined_text"] = combined.strip()

        return result


class RecipeTextExtractor:
    """
    Extracts raw text content from URLs and local documents.
    """

    @staticmethod
    def extract_from_url(url: str) -> tuple[str, str]:
        """
        Fetch HTML from URL and strip tags to get readable plain text.

        :param url: Web page URL to fetch.
        :return: Tuple of (extracted_text, title).
        :raises RuntimeError: If URL cannot be retrieved.
        """
        print(f"[Web] Extrayendo contenido de la URL: {url}...", flush=True)
        headers = {
            "User-Agent": (
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            )
        }
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                charset = response.headers.get_content_charset() or "utf-8"
                html_bytes = response.read()
                html_text = html_bytes.decode(charset, errors="replace")
        except Exception as e:
            raise RuntimeError(f"Failed to fetch content from URL '{url}': {e}") from e

        # Extract title
        title_match = re.search(r"<title[^>]*>(.*?)</title>", html_text, re.IGNORECASE | re.DOTALL)
        title = title_match.group(1).strip() if title_match else ""

        # Extract meta description / og:description
        meta_desc = ""
        meta_desc_match = re.search(
            r'<meta\s+(?:name|property)=["\'](?:description|og:description)["\']\s+content=["\'](.*?)["\']',
            html_text,
            re.IGNORECASE | re.DOTALL,
        )
        if not meta_desc_match:
            meta_desc_match = re.search(
                r'<meta\s+content=["\'](.*?)["\']\s+(?:name|property)=["\'](?:description|og:description)["\']',
                html_text,
                re.IGNORECASE | re.DOTALL,
            )
        if meta_desc_match:
            meta_desc = meta_desc_match.group(1).strip()

        # Remove scripts, styles, header, footer, nav
        cleaned = re.sub(r"<(script|style|nav|footer|header|aside)[^>]*>.*?</\1>", " ", html_text, flags=re.IGNORECASE | re.DOTALL)
        # Strip all HTML tags
        text = re.sub(r"<[^>]+>", " ", cleaned)
        # Unescape HTML entities
        text = html.unescape(text)
        meta_desc = html.unescape(meta_desc)
        title = html.unescape(title)

        if meta_desc:
            text = f"Title: {title}\nDescription: {meta_desc}\n\nContent:\n{text}"

        # Collapse whitespace
        text = re.sub(r"\s+", " ", text).strip()
        print(f"[Web] ✓ Texto extraído: '{title}' ({len(text)} caracteres)", flush=True)

        return text, title

    @staticmethod
    def extract_from_file(file_path: str) -> tuple[str, bytes, str]:
        """
        Read local document or file content and determine mime type.

        :param file_path: Path to the local file.
        :return: Tuple of (extracted_text, raw_bytes, mime_type).
        :raises FileNotFoundError: If file does not exist.
        :raises RuntimeError: If file cannot be read.
        """
        if not path.isfile(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        mime_type, _encoding = mimetypes.guess_type(file_path)
        if not mime_type:
            mime_type = "application/octet-stream"

        print(f"[Documento] Leyendo archivo local '{file_path}' (MIME: {mime_type})...", flush=True)

        with open(file_path, "rb") as f:
            raw_bytes = f.read()

        text = ""
        # Handle plain text, markdown, html, json
        if mime_type.startswith("text/") or file_path.endswith((".md", ".txt", ".html", ".htm", ".json", ".rst")):
            try:
                text = raw_bytes.decode("utf-8")
            except UnicodeDecodeError:
                text = raw_bytes.decode("latin-1", errors="replace")
        elif file_path.lower().endswith(".pdf"):
            # Attempt to extract text from PDF if pypdf or PyPDF2 is installed
            try:
                import pypdf
                import io
                reader = pypdf.PdfReader(io.BytesIO(raw_bytes))
                text = "\n".join([page.extract_text() or "" for page in reader.pages])
            except ImportError:
                # Fallback basic string extraction for ASCII streams
                text = re.sub(r"[^\x20-\x7E\n\r\t]", " ", raw_bytes.decode("latin-1", errors="replace"))
        else:
            # Generic binary fallback string extraction
            text = raw_bytes.decode("utf-8", errors="replace")

        # Collapse whitespace
        text = re.sub(r"[ \t]+", " ", text).strip()
        print(f"[Documento] ✓ Texto extraído ({len(text)} caracteres, {len(raw_bytes)} bytes)", flush=True)
        return text, raw_bytes, mime_type


class ProductMatcher:
    """
    High-confidence heuristic matcher to safely map recipe ingredient names
    to existing user products without introducing false positive matches.
    """

    STOPWORDS = {
        "de", "del", "la", "el", "los", "las", "un", "una", "unos", "unas",
        "para", "con", "sin", "y", "e", "o", "u", "al", "en", "por",
        "fresco", "fresca", "frescos", "frescas", "natural", "naturales",
        "crudo", "cruda", "crudos", "crudas", "troceado", "troceada", "picado", "picada",
        "rallado", "rallada", "cocido", "cocida", "frito", "frita", "asado", "asada",
        "fresh", "raw", "chopped", "diced", "sliced", "grated", "cooked", "fried",
    }

    # Groups of mutually exclusive modifier tokens. If ingredient and product specify different
    # tokens from the same group, they MUST NOT match.
    MUTUALLY_EXCLUSIVE_MODIFIER_GROUPS = [
        {"oliva", "girasol", "coco", "sesamo", "maiz", "soja", "palma", "colza", "cacahuete", "aguacate"},
        {"entera", "desnatada", "semidesnatada", "skim", "whole", "semi", "descremada"},
        {"blanco", "tinto", "rosado", "negro", "verde", "rojo", "amarillo", "morado", "white", "red", "black", "green", "yellow"},
        {"vaca", "cabra", "oveja", "soja", "avena", "almendra", "arroz", "coco", "avellana"},
        {"trigo", "centeno", "espelta", "maiz", "maicena", "arroz", "avena", "garbanzo"},
        {"dulce", "salado", "amargo", "picante", "agridulce", "sweet", "salty", "spicy"},
        {"pechuga", "muslo", "ala", "lomo", "solomillo", "costilla", "higado", "picada"},
        {"molido", "grano", "polvo", "entero", "hoja", "rama"},
    ]

    CONFIDENCE_THRESHOLD = 0.85

    @classmethod
    def normalize_text(cls, text: str) -> str:
        """
        Normalize text by lowercasing, removing accents, punctuation, and extra whitespace.

        :param text: Input string.
        :return: Normalized string.
        """
        if not text:
            return ""
        text = text.lower().strip()
        nfkd = unicodedata.normalize("NFKD", text)
        no_accents = "".join(c for c in nfkd if not unicodedata.combining(c))
        cleaned = re.sub(r"[^\w\s]", " ", no_accents)
        return re.sub(r"\s+", " ", cleaned).strip()

    @classmethod
    def singularize_word(cls, word: str) -> str:
        """
        Basic singularization for Spanish and English words.

        :param word: Word string.
        :return: Singularized word.
        """
        if len(word) <= 3:
            return word
        if word.endswith("ces"):
            return word[:-3] + "z"
        if word.endswith("es") and word[-3] not in "aeiou":
            return word[:-2]
        if word.endswith("s") and not word.endswith("ss"):
            return word[:-1]
        return word

    @classmethod
    def extract_meaningful_tokens(cls, text: str) -> tuple[list[str], set[str]]:
        """
        Extract normalized, singularized, non-stopword tokens from a text string.

        :param text: Input string.
        :return: Tuple of (ordered_tokens_list, tokens_set).
        """
        norm = cls.normalize_text(text)
        tokens = [cls.singularize_word(w) for w in norm.split() if w and w not in cls.STOPWORDS]
        return tokens, set(tokens)

    @classmethod
    def has_conflicting_modifiers(cls, ing_tokens_set: set[str], prod_tokens_set: set[str]) -> bool:
        """
        Check if ingredient and product contain mutually exclusive distinguishing tokens.

        :param ing_tokens_set: Set of meaningful tokens in ingredient.
        :param prod_tokens_set: Set of meaningful tokens in product.
        :return: True if conflicting modifiers exist, False otherwise.
        """
        for group in cls.MUTUALLY_EXCLUSIVE_MODIFIER_GROUPS:
            ing_intersect = ing_tokens_set.intersection(group)
            prod_intersect = prod_tokens_set.intersection(group)
            if ing_intersect and prod_intersect and ing_intersect != prod_intersect:
                return True
        return False

    @classmethod
    def calculate_confidence(cls, ing_name: str, prod_name: str) -> float:
        """
        Calculate match confidence score between an ingredient name and a product name.

        :param ing_name: Ingredient name from recipe.
        :param prod_name: Product name from user database.
        :return: Float score between 0.0 and 1.0.
        """
        if not ing_name or not prod_name:
            return 0.0

        raw_ing = ing_name.strip().lower()
        raw_prod = prod_name.strip().lower()

        # 1. Exact raw match
        if raw_ing == raw_prod:
            return 1.0

        norm_ing = cls.normalize_text(ing_name)
        norm_prod = cls.normalize_text(prod_name)

        # 2. Exact normalized match (ignoring accents, case, punctuation)
        if norm_ing == norm_prod:
            return 0.98

        ing_tokens, ing_set = cls.extract_meaningful_tokens(ing_name)
        prod_tokens, prod_set = cls.extract_meaningful_tokens(prod_name)

        if not ing_tokens or not prod_tokens:
            return 0.0

        # Check for conflicting modifiers (e.g. olive oil vs sunflower oil)
        if cls.has_conflicting_modifiers(ing_set, prod_set):
            return 0.0

        # 3. Exact token set match (ignoring word order and stopwords)
        if ing_set == prod_set:
            return 0.95

        stem_ing = " ".join(ing_tokens)
        stem_prod = " ".join(prod_tokens)

        # 4. Exact stemmed sequence match
        if stem_ing == stem_prod:
            return 0.94

        # 5. Sequence similarity over normalized and stemmed representations
        ratio_norm = difflib.SequenceMatcher(None, norm_ing, norm_prod).ratio()
        ratio_stem = difflib.SequenceMatcher(None, stem_ing, stem_prod).ratio()
        base_ratio = max(ratio_norm, ratio_stem)

        # Ensure that if the ingredient has key tokens, they are predominantly in the product
        if len(ing_set) == 1 and len(prod_set) == 1:
            single_ing = list(ing_set)[0]
            single_prod = list(prod_set)[0]
            if single_ing != single_prod:
                token_sim = difflib.SequenceMatcher(None, single_ing, single_prod).ratio()
                if token_sim < 0.88 or min(len(single_ing), len(single_prod)) <= 3:
                    return 0.0
                return token_sim * 0.9

        # If one token set is a subset of the other, check if all essential tokens are matched
        if ing_set.issubset(prod_set) or prod_set.issubset(ing_set):
            common_count = len(ing_set.intersection(prod_set))
            total_count = max(len(ing_set), len(prod_set))
            subset_ratio = common_count / total_count
            if subset_ratio >= 0.80:
                return max(base_ratio, subset_ratio * 0.92)

        return base_ratio

    @classmethod
    def find_best_product(cls, ing_name: str, candidate_products) -> tuple[models.Products | None, float]:
        """
        Find the single product with the highest confidence score exceeding CONFIDENCE_THRESHOLD.

        :param ing_name: Name of ingredient from recipe.
        :param candidate_products: Iterable / QuerySet of user Products.
        :return: Tuple (best_product, confidence_score) or (None, 0.0).
        """
        best_product = None
        best_score = 0.0

        for product in candidate_products:
            p_name = getattr(product, "name", "")
            if not p_name or not p_name.strip():
                continue

            score = cls.calculate_confidence(ing_name, p_name)
            if score > best_score:
                best_score = score
                best_product = product
                if score >= 0.98:  # Near perfect match, early exit
                    break

        if best_score >= cls.CONFIDENCE_THRESHOLD:
            return best_product, best_score
        return None, best_score


class RecipeImporter:
    """
    Coordinates LLM parsing, database object creation (Recipes, RecipesLinks,
    RecipesCategories), and automatic elaboration generation.
    """

    MEASURE_MAP = {
        "g": 1,
        "gr": 1,
        "gram": 1,
        "grams": 1,
        "gramo": 1,
        "gramos": 1,
        "kg": 1,  # Will convert amount * 1000
        "kilo": 1,
        "kilos": 1,
        "ml": 2,
        "milliliter": 2,
        "milliliters": 2,
        "mililitro": 2,
        "mililitros": 2,
        "cl": 2,  # Will convert amount * 10
        "l": 2,   # Will convert amount * 1000
        "litro": 2,
        "litros": 2,
        "tbsp": 3,
        "cucharada": 3,
        "cucharadas": 3,
        "cda": 3,
        "table spoon": 3,
        "tablespoon": 3,
        "tsp": 4,
        "cucharadita": 4,
        "cucharaditas": 4,
        "cdita": 4,
        "tea spoon": 4,
        "teaspoon": 4,
        "cup": 5,
        "taza": 5,
        "tazas": 5,
    }

    def __init__(self, ollama_client: OllamaClient = None, locale: str = "es"):
        """
        Initialize the recipe importer.

        :param ollama_client: Optional custom OllamaClient instance.
        :param locale: Default locale/language code for imports and translations (default: "es").
        """
        self.client = ollama_client or OllamaClient()
        self.locale = locale or "es"

    def parse_recipe_with_llm(
        self,
        content_text: str,
        audio_base64: str = None,
        user: User = None,
        locale: str = None,
    ) -> dict:
        """
        Send recipe text and optional audio to Ollama and obtain structured JSON.

        :param content_text: Plain text extracted from URL, transcript, or document.
        :param audio_base64: Optional base64 encoded audio track.
        :param user: Optional target user to provide user-specific products hint to LLM.
        :param locale: Optional locale override (defaults to self.locale).
        :return: Parsed dictionary with recipe attributes.
        """
        # Truncate content text if excessively large to stay within context
        truncated_text = content_text[:12000]
        loc = (locale or self.locale or "es").split("_")[0].lower()
        lang_map = {
            "es": "Spanish",
            "en": "English",
            "fr": "French",
            "de": "German",
            "it": "Italian",
            "pt": "Portuguese",
        }
        lang_name = lang_map.get(loc, "Spanish" if loc.startswith("es") else "English")

        print(f"[Ollama] Enviando contenido al LLM (modelo: '{self.client.model}', idioma: {lang_name})...", flush=True)
        if audio_base64:
            print("[Ollama] Adjuntando pista de audio codificada en Base64...", flush=True)

        system_prompt = (
            f"You are a professional culinary assistant. Your task is to analyze the provided text and audio, "
            f"summarize the recipe clearly and concisely in {lang_name}, and extract recipe information into a strict JSON format.\n"
            "Respond ONLY with valid JSON conforming to the requested schema. Do not include markdown formatting outside the JSON."
        )

        existing_categories = list(models.RecipesCategories.objects.values_list("name", flat=True))
        if existing_categories:
            cats_sample = ", ".join(f"'{c}'" for c in existing_categories[:30])
            cats_prompt_line = f"- \"categories\": (array of strings) List of categories chosen ONLY from available ones (e.g. [{cats_sample}]).\n"
        else:
            cats_prompt_line = "- \"categories\": (array of strings) List of suitable recipe categories.\n"

        user_products = []
        if user:
            user_products = list(
                models.Products.objects.filter(user=user, obsolete=False)
                .exclude(name__isnull=True)
                .exclude(name__exact="")
                .values_list("name", flat=True)[:50]
            )
        if user_products:
            prod_sample = ", ".join(f"'{p}'" for p in user_products)
            ing_prompt_line = f"- \"ingredients\": (array of objects) Whenever possible, match ingredient names with user's available products: [{prod_sample}]. Each object must have:\n"
        else:
            ing_prompt_line = "- \"ingredients\": (array of objects) Each object must have:\n"

        prompt = (
            f"Analyze the following text, summarize the recipe clearly and concisely in {lang_name}, and extract the recipe information into a single JSON object with these exact keys:\n"
            f"- \"name\": (string) Recipe title in {lang_name}.\n"
            f"- \"comment\": (string) Concise summary or description of the recipe in {lang_name}.\n"
            "- \"food_type\": (string) Main category (e.g., 'Homemade food', 'Meat', 'Fish', 'Vegetables', 'Pasta', 'Bakery', 'Eggs', 'Dessert').\n"
            f"{cats_prompt_line}"
            "- \"diners\": (integer) Number of servings/diners (default 4 if not specified).\n"
            f"{ing_prompt_line}"
            "    - \"name\": (string) Ingredient/Product name.\n"
            "    - \"amount\": (number) Quantity needed.\n"
            "    - \"unit\": (string) Unit of measure ('g', 'ml', 'tbsp', 'tsp', 'cup', 'unit').\n"
            "    - \"comment\": (string) Preparation notes (e.g., 'chopped', 'diced', 'peeled', 'at room temperature').\n"
            f"- \"steps\": (string) Summarized, concise, step-by-step preparation instructions in {lang_name} in Markdown format.\n\n"
            f"Recipe source text:\n{truncated_text}\n"
        )

        result_json = self.client.generate(
            prompt=prompt,
            system_prompt=system_prompt,
            format_json=True,
            audio_base64=audio_base64,
        )
        if isinstance(result_json, dict):
            print(f"[Ollama] ✓ Respuesta estructurada recibida: '{result_json.get('name')}' ({len(result_json.get('ingredients', []))} ingredientes)", flush=True)
        return result_json

    @transaction.atomic
    def save_recipe(
        self,
        recipe_data: dict,
        user: User,
        source_url: str = None,
        source_file_info: tuple[str, bytes, str] = None,
        locale: str = None,
    ) -> models.Recipes:
        """
        Persist Recipe, RecipesLinks, and RecipesCategories to database.

        :param recipe_data: Structured recipe data from LLM.
        :param user: Owner user for the recipe.
        :param source_url: Optional source URL for RecipesLinks.
        :param source_file_info: Optional tuple (filename, raw_bytes, mime_type) for RecipesLinks.
        :param locale: Optional locale override for i18n notices.
        :return: Created Recipes model instance.
        """
        loc = locale or self.locale or "es"
        translation.activate(loc)

        # Resolve FoodType
        food_type_name = recipe_data.get("food_type", "Homemade food")
        food_type = (
            models.FoodTypes.objects.filter(name__icontains=food_type_name).first()
            or models.FoodTypes.objects.filter(name__icontains="Homemade food").first()
            or models.FoodTypes.objects.first()
        )

        ai_notice = _("Generated by AI")
        raw_name = recipe_data.get("name", "Receta sin título").strip()
        if f"({ai_notice})" not in raw_name and "(Generated by AI)" not in raw_name and "(Generatated by IA)" not in raw_name and "(Generado por IA)" not in raw_name:
            final_name = f"{raw_name} ({ai_notice})"
        else:
            final_name = raw_name

        print(f"[BD] Guardando receta '{final_name}' (Tipo: {food_type.name})...", flush=True)

        recipe = models.Recipes()
        recipe.name = final_name
        recipe.datetime = timezone.now()
        recipe.food_types = food_type
        recipe.obsolete = False
        recipe.user = user
        recipe.comment = recipe_data.get("comment", "")
        recipe.guests = False
        recipe.soon = False
        recipe.save()
        print(f"[BD] ✓ Receta creada con ID {recipe.id}", flush=True)

        # Handle Categories: only associate existing categories, do not create new ones
        category_names = recipe_data.get("categories", [])
        added_categories = []
        if isinstance(category_names, list):
            for cat_name in category_names:
                if isinstance(cat_name, str) and cat_name.strip():
                    name_clean = cat_name.strip()
                    cat = (
                        models.RecipesCategories.objects.filter(name__iexact=name_clean).first()
                        or models.RecipesCategories.objects.filter(name__icontains=name_clean).first()
                    )
                    if cat:
                        recipe.recipes_categories.add(cat)
                        added_categories.append(cat.name)
                    else:
                        print(f"[BD] ℹ Categoría '{name_clean}' no encontrada en la base de datos (omitida)", flush=True)

        if added_categories:
            print(f"[BD] ✓ Categorías vinculadas: {added_categories}", flush=True)

        # Handle URL Link
        if source_url:
            yt_video_id = YouTubeHelper.get_video_id(source_url)
            if yt_video_id:
                link_type = (
                    models.RecipesLinksTypes.objects.filter(name__icontains="Video link").first()
                    or models.RecipesLinksTypes.objects.get(pk=1)
                )
                rl_desc = f"Vídeo de YouTube: {recipe.name}"
            else:
                link_type = (
                    models.RecipesLinksTypes.objects.filter(name__icontains="Web page link").first()
                    or models.RecipesLinksTypes.objects.get(pk=3)
                )
                rl_desc = f"Fuente web: {recipe.name}"

            rl = models.RecipesLinks()
            rl.datetime = timezone.now()
            rl.description = rl_desc
            rl.type = link_type
            rl.link = source_url
            rl.recipes = recipe
            rl.save()
            print(f"[BD] ✓ Enlace guardado: '{source_url}' ({link_type.name})", flush=True)

            # If origin is YouTube, fetch thumbnail and set as Main Photo
            if yt_video_id:
                thumb_result = YouTubeHelper.fetch_thumbnail(yt_video_id)
                if thumb_result:
                    thumb_bytes, thumb_mime = thumb_result
                    thumb_file = models.Files()
                    thumb_file.content = thumb_bytes
                    thumb_file.size = len(thumb_bytes)
                    thumb_file.mime = thumb_mime
                    thumb_file.user = user
                    thumb_file.save()

                    main_photo_type = (
                        models.RecipesLinksTypes.objects.filter(pk=getattr(models.eRecipeLink, "MainPhoto", 7)).first()
                        or models.RecipesLinksTypes.objects.filter(name__icontains="Main photo").first()
                        or models.RecipesLinksTypes.objects.get(pk=7)
                    )

                    main_rl = models.RecipesLinks()
                    main_rl.datetime = timezone.now()
                    main_rl.description = f"Imagen principal del vídeo: {recipe.name}"
                    main_rl.type = main_photo_type
                    main_rl.files = thumb_file
                    main_rl.recipes = recipe
                    main_rl.save()
                    print(f"[BD] ✓ Snapshot guardado como Main Photo (Files ID: {thumb_file.id})", flush=True)

        # Handle File Link
        if source_file_info:
            file_name, raw_bytes, mime_type = source_file_info
            file_obj = models.Files()
            file_obj.content = raw_bytes
            file_obj.size = len(raw_bytes)
            file_obj.mime = mime_type
            file_obj.user = user
            file_obj.save()

            link_type = (
                models.RecipesLinksTypes.objects.filter(name__icontains="Document file").first()
                or models.RecipesLinksTypes.objects.get(pk=6)
            )
            rl = models.RecipesLinks()
            rl.datetime = timezone.now()
            rl.description = f"Documento: {path.basename(file_name)}"
            rl.type = link_type
            rl.files = file_obj
            rl.recipes = recipe
            rl.save()
            print(f"[BD] ✓ Documento adjunto guardado: '{path.basename(file_name)}' (Files ID: {file_obj.id})", flush=True)

        return recipe

    @transaction.atomic
    def create_automatic_elaboration(
        self,
        recipe: models.Recipes,
        recipe_data: dict,
        user: User,
        locale: str = None,
    ) -> models.Elaborations:
        """
        Create an automatic Elaboration for the recipe with ingredients and text steps.

        :param recipe: The parent Recipes model.
        :param recipe_data: Structured recipe data containing ingredients and steps.
        :param user: User performing the action.
        :param locale: Optional locale override for i18n notices.
        :return: Created Elaborations model instance.
        """
        loc = locale or self.locale or "es"
        translation.activate(loc)

        diners = recipe_data.get("diners", 4)
        try:
            diners = int(diners)
            if diners <= 0:
                diners = 4
        except (ValueError, TypeError):
            diners = 4

        print(f"[Elaboración] Creando elaboración automática ({diners} comensales) para receta ID {recipe.id}...", flush=True)

        elaboration = models.Elaborations()
        elaboration.recipes = recipe
        elaboration.diners = diners
        elaboration.automatic = False
        elaboration.automatic_adaptation_step = ""
        elaboration.save()

        ingredients = recipe_data.get("ingredients", [])
        through_list = []

        print(f"[Elaboración] Procesando {len(ingredients)} ingredientes...", flush=True)

        for ing in ingredients:
            if not isinstance(ing, dict):
                continue

            ing_name = str(ing.get("name", "")).strip()
            if not ing_name or len(ing_name) < 2:
                continue

            # Resolve product - only look up valid, non-empty existing products for the specific user using high-confidence matching
            target_user = user or recipe.user
            user_products = (
                models.Products.objects.filter(user=target_user, obsolete=False)
                .exclude(name__isnull=True)
                .exclude(name__exact="")
                .exclude(name__regex=r"^\s*$")
            )

            product, confidence = ProductMatcher.find_best_product(ing_name, user_products)

            if not product or confidence < ProductMatcher.CONFIDENCE_THRESHOLD:
                user_name_display = getattr(target_user, "username", str(target_user)) if target_user else "desconocido"
                conf_pct = int(confidence * 100)
                print(
                    f"  - Ingrediente ignorado (no coincide con alta confianza para el usuario '{user_name_display}', coincidencia={conf_pct}%): '{ing_name}'",
                    flush=True,
                )
                continue

            # Resolve unit & measure type
            unit_str = str(ing.get("unit", "g")).lower().strip()
            measure_id = self.MEASURE_MAP.get(unit_str, 1)

            # Resolve amount
            raw_amount = ing.get("amount", 100)
            try:
                amount_num = float(raw_amount)
                # Handle kg or liter conversions
                if unit_str in ["kg", "kilo", "kilos", "l", "litro", "litros"]:
                    amount_num *= 1000
                elif unit_str in ["cl"]:
                    amount_num *= 10
                amount_dec = Decimal(str(round(amount_num, 3)))
            except (ValueError, TypeError):
                amount_dec = Decimal("100.000")

            comment = str(ing.get("comment", "")).strip()[:100]

            measure_type = models.MeasuresTypes.objects.filter(pk=measure_id).first()
            if not measure_type:
                measure_type = models.MeasuresTypes.objects.get(pk=1)

            pi = models.ElaborationsProductsInThrough()
            pi.elaborations = elaboration
            pi.products = product
            pi.measures_types = measure_type
            pi.amount = amount_dec
            pi.comment = comment if comment else None
            pi.ni = True
            pi.automatic_percentage = 100
            pi.save()
            through_list.append(pi)
            print(f"  + Ingrediente vinculado: '{product.name}' ({amount_dec} {measure_type.name})", flush=True)

        # ElaborationsTexts
        steps_text = recipe_data.get("steps", "")
        if not steps_text:
            steps_text = recipe_data.get("comment", "Preparación según la receta.")

        # Enrich text with ingredient mention spans if ingredient names appear
        for pi in through_list:
            p_name = pi.products.name
            span = models.ElaborationsTexts.span_ingredient(pi.id, pi.fullname())
            # Replace case-insensitively product name with mention span
            pattern = re.compile(re.escape(p_name), re.IGNORECASE)
            steps_text = pattern.sub(span, steps_text, count=1)

        # Append i18n AI notice at the end of the recipe elaboration text
        ai_notice = _("Generated by AI")
        if not steps_text.endswith("\n"):
            steps_text += f"\n\n({ai_notice})"
        else:
            steps_text += f"\n({ai_notice})"

        elaboration_text = models.ElaborationsTexts()
        elaboration_text.elaborations = elaboration
        elaboration_text.text = steps_text
        elaboration_text.save()
        print(f"[Elaboración] ✓ Pasos de elaboración guardados ({len(steps_text)} caracteres)", flush=True)

        return elaboration

    @transaction.atomic
    def create_elaboration_from_recipe_links(self, recipe: models.Recipes, user: User, locale: str = None) -> models.Elaborations:
        """
        Generate an automatic elaboration for an existing recipe by reading its associated RecipesLinks.

        :param recipe: The existing Recipe instance.
        :param user: User executing the action.
        :param locale: Optional locale override.
        :return: Created Elaborations model instance.
        """
        loc = locale or self.locale or "es"
        translation.activate(loc)

        combined_text = f"Receta: {recipe.name}\n{recipe.comment or ''}\n"
        audio_base64 = None

        for link in recipe.recipes_links.all():
            if link.link:
                yt_id = YouTubeHelper.get_video_id(link.link)
                if yt_id:
                    try:
                        yt_data = YouTubeHelper.extract_full_youtube_data(link.link, yt_id, locale=loc)
                        combined_text += f"\n--- Contenido de YouTube ({link.link}) ---\n{yt_data['combined_text']}\n"
                        if yt_data.get("audio_base64"):
                            audio_base64 = yt_data["audio_base64"]
                    except Exception as e:
                        logger.warning("Could not extract full YouTube data for %s: %s", link.link, e)
                else:
                    try:
                        url_text, _title = RecipeTextExtractor.extract_from_url(link.link)
                        combined_text += f"\n--- Contenido de enlace {link.link} ---\n{url_text}\n"
                    except Exception as e:
                        logger.warning("Could not extract text from recipe link %s: %s", link.link, e)
            elif link.files and link.files.content:
                try:
                    content_str = bytes(link.files.content).decode("utf-8", errors="replace")
                    combined_text += f"\n--- Contenido de archivo ---\n{content_str}\n"
                except Exception as e:
                    logger.warning("Could not decode file content for recipe %s: %s", recipe.id, e)

        recipe_data = self.parse_recipe_with_llm(combined_text, audio_base64=audio_base64, user=user, locale=loc)
        return self.create_automatic_elaboration(recipe, recipe_data, user, locale=loc)

    @transaction.atomic
    def import_recipe(
        self,
        url: str = None,
        file_path: str = None,
        user: User = None,
        create_elaboration: bool = True,
        locale: str = None,
    ) -> tuple[models.Recipes, models.Elaborations | None]:
        """
        Full workflow: extracts text from source, queries Ollama LLM,
        creates Recipe, RecipesLinks, RecipesCategories, and automatic Elaboration.

        :param url: URL to scrape recipe from.
        :param file_path: Path to local document file.
        :param user: Owner user for created entities.
        :param create_elaboration: If True, creates automatic Elaboration with ingredients & steps.
        :param locale: Optional locale override (defaults to self.locale).
        :return: Tuple of (created_recipe, created_elaboration).
        :raises ValueError: If neither url nor file_path is provided, or no user available.
        """
        loc = locale or self.locale or "es"
        translation.activate(loc)

        if not url and not file_path:
            raise ValueError("Must provide either a URL or a file path.")

        if not user:
            user = User.objects.filter(is_superuser=True).first() or User.objects.first()
            if not user:
                raise ValueError("No user found in database to assign recipe to.")

        source_file_info = None
        audio_base64 = None
        if url:
            yt_id = YouTubeHelper.get_video_id(url)
            if yt_id:
                yt_data = YouTubeHelper.extract_full_youtube_data(url, yt_id, locale=loc)
                extracted_text = yt_data["combined_text"]
                audio_base64 = yt_data.get("audio_base64")
            else:
                extracted_text, _title = RecipeTextExtractor.extract_from_url(url)
        else:
            extracted_text, raw_bytes, mime_type = RecipeTextExtractor.extract_from_file(file_path)
            source_file_info = (file_path, raw_bytes, mime_type)

        # Parse with LLM (passing text and audio when available, and user for product suggestions)
        recipe_data = self.parse_recipe_with_llm(extracted_text, audio_base64=audio_base64, user=user, locale=loc)

        # Save Recipe, Categories, Links
        recipe = self.save_recipe(
            recipe_data=recipe_data,
            user=user,
            source_url=url,
            source_file_info=source_file_info,
            locale=loc,
        )

        # Create Elaboration
        elaboration = None
        if create_elaboration:
            elaboration = self.create_automatic_elaboration(recipe, recipe_data, user, locale=loc)

        return recipe, elaboration


class Command(BaseCommand):
    """
    Django management command for recipe importation and automatic elaboration generation.
    """

    help = (
        "Imports a recipe from a URL or local document using local Ollama LLM, "
        "populates Recipes, RecipesLinks, RecipesCategories, and creates an automatic Elaboration."
    )

    def add_arguments(self, parser):
        """
        Register CLI arguments.
        """
        parser.add_argument(
            "--url",
            type=str,
            help="Web page URL containing the recipe to import.",
            default=None,
        )
        parser.add_argument(
            "--document",
            "--file",
            type=str,
            dest="document",
            help="Local document/file path containing the recipe.",
            default=None,
        )
        parser.add_argument(
            "--locale",
            type=str,
            help="Locale/language code for recipe import and translation (e.g., 'es', 'en'). Default is 'es'.",
            default="es",
        )
        parser.add_argument(
            "--user_id",
            type=int,
            help="ID of the User who will own the imported recipe.",
            default=None,
        )
        parser.add_argument(
            "--username",
            type=str,
            help="Username of the User who will own the imported recipe.",
            default=None,
        )
        parser.add_argument(
            "--from-recipe-id",
            type=int,
            dest="from_recipe_id",
            help="ID of an existing recipe to generate an automatic elaboration for, using its recipes_links.",
            default=None,
        )
        parser.add_argument(
            "--no-elaboration",
            action="store_true",
            help="If set, only creates the Recipe and RecipesLinks without creating an automatic Elaboration.",
            default=False,
        )

    def handle(self, *args, **options):
        """
        Execute command logic.
        """
        locale = options.get("locale", "es") or "es"
        current_language = translation.get_language()
        translation.activate(locale)

        try:
            importer = RecipeImporter(locale=locale)

            # Resolve User
            user = None
            if options.get("user_id"):
                try:
                    user = User.objects.get(pk=options["user_id"])
                except User.DoesNotExist:
                    raise CommandError(f"User with ID {options['user_id']} does not exist.")
            elif options.get("username"):
                try:
                    user = User.objects.get(username=options["username"])
                except User.DoesNotExist:
                    raise CommandError(f"User with username '{options['username']}' does not exist.")
            else:
                user = User.objects.filter(is_superuser=True).first() or User.objects.first()
                if not user:
                    raise CommandError("No users exist in the database. Please create a user first.")

            # Mode 1: Create automatic elaboration from existing recipe's recipes_links
            if options.get("from_recipe_id"):
                recipe_id = options["from_recipe_id"]
                try:
                    recipe = models.Recipes.objects.get(pk=recipe_id)
                except models.Recipes.DoesNotExist:
                    raise CommandError(f"Recipe with ID {recipe_id} not found.")

                self.stdout.write(self.style.NOTICE(f"Processing recipe '{recipe.name}' (ID: {recipe.id}) from its recipes_links..."))
                try:
                    elaboration = importer.create_elaboration_from_recipe_links(recipe, user=user, locale=locale)
                    self.stdout.write(
                        self.style.SUCCESS(
                            f"Successfully created automatic elaboration (ID: {elaboration.id}) for recipe '{recipe.name}' with {elaboration.diners} diners."
                        )
                    )
                except Exception as e:
                    raise CommandError(f"Failed to generate elaboration from recipe links: {e}") from e
                return

            # Mode 2: Import new recipe from URL or document
            url = options.get("url")
            document = options.get("document")

            if not url and not document:
                raise CommandError("You must provide either --url, --document (or --file), or --from-recipe-id.")

            source_desc = f"URL '{url}'" if url else f"file '{document}'"
            self.stdout.write(self.style.NOTICE(f"Importing recipe from {source_desc} using Ollama LLM (locale: {locale})..."))

            try:
                recipe, elaboration = importer.import_recipe(
                    url=url,
                    file_path=document,
                    user=user,
                    create_elaboration=not options.get("no_elaboration"),
                    locale=locale,
                )
            except Exception as e:
                raise CommandError(f"Error importing recipe: {e}") from e

            self.stdout.write(self.style.SUCCESS(f"Successfully created Recipe '{recipe.name}' (ID: {recipe.id})"))
            self.stdout.write(f"  - Food Type: {recipe.food_types.name}")
            self.stdout.write(f"  - Categories: {', '.join([c.name for c in recipe.recipes_categories.all()]) or 'None'}")
            self.stdout.write(f"  - Associated Links: {recipe.recipes_links.count()}")

            if elaboration:
                self.stdout.write(
                    self.style.SUCCESS(
                        f"Successfully created automatic Elaboration (ID: {elaboration.id}, {elaboration.diners} diners)"
                    )
                )
                pi_count = models.ElaborationsProductsInThrough.objects.filter(elaborations=elaboration).count()
                self.stdout.write(f"  - Ingredients added: {pi_count}")
        finally:
            if current_language:
                translation.activate(current_language)
