# Generated by Django 4.0.3 on 2022-04-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formats',
            name='last',
        ),
        migrations.AddField(
            model_name='products',
            name='formats',
            field=models.ManyToManyField(to='calories_tracker.formats'),
        ),
        migrations.AddField(
            model_name='systemproducts',
            name='formats',
            field=models.ManyToManyField(to='calories_tracker.formats'),
        ),
    ]
