# Generated by Django 4.1.3 on 2022-11-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0005_elaborations_recipes_recipeslinkstypes_stirtypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaborationssteps',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
