# Generated by Django 4.1.3 on 2022-11-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0006_alter_elaborationssteps_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='guests',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='soon',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='valoration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
