# Generated by Django 4.1.3 on 2022-11-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0007_recipes_guests_recipes_soon_recipes_valoration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeslinks',
            name='content',
        ),
        migrations.AlterField(
            model_name='recipeslinks',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipes_links', to='calories_tracker.recipes'),
        ),
    ]
