# Generated by Django 4.1.3 on 2022-11-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0009_recipeslinks_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elaborations',
            name='robot',
        ),
    ]
