# Generated by Django 4.1.3 on 2022-11-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0010_remove_elaborations_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaborations',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='elaborations', to='calories_tracker.recipes'),
        ),
    ]
