# Generated by Django 4.1.3 on 2022-11-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0012_rename_products_in_elaborations_elaborations_products_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaborationssteps',
            name='elaborations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='elaborations_steps', to='calories_tracker.elaborations'),
        ),
    ]
