# Generated by Django 4.1.3 on 2022-11-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0013_alter_elaborationssteps_elaborations'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaborationssteps',
            name='products_in_step',
            field=models.ManyToManyField(blank=True, related_name='products_in_step', to='calories_tracker.elaborationsproductsinthrough'),
        ),
    ]
