# Generated by Django 4.1.3 on 2022-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0014_elaborationssteps_products_in_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaborationssteps',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
