# Generated by Django 4.1.3 on 2022-11-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0015_elaborationssteps_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'recipes_categories',
                'managed': True,
            },
        ),
    ]
