# Generated by Django 4.1.3 on 2022-11-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0016_recipescategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipes_categories',
            field=models.ManyToManyField(blank=True, to='calories_tracker.recipescategories'),
        ),
    ]
