# Generated by Django 4.1.3 on 2022-11-30 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0017_recipes_recipes_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuresTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'measures_types',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='systemproducts',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
