# Generated by Django 4.1.3 on 2022-12-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0021_elaboratedproducts_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElaborationsExperiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('experience', models.TextField()),
                ('elaborations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborations_experiences', to='calories_tracker.elaborations')),
            ],
            options={
                'db_table': 'elaborations_experiences',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElaborationsContainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('elaborations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborations_containers', to='calories_tracker.elaborations')),
            ],
            options={
                'db_table': 'elaborations_containers',
                'managed': True,
            },
        ),
    ]
