# Generated by Django 4.1.3 on 2022-12-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0022_elaborationsexperiences_elaborationscontainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaborationssteps',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='container', to='calories_tracker.elaborationscontainers'),
        ),
        migrations.AddField(
            model_name='elaborationssteps',
            name='container_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='container_to', to='calories_tracker.elaborationscontainers'),
        ),
    ]
