# Generated by Django 4.1.3 on 2022-12-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0023_elaborationssteps_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='stir_types',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='temperatures_types',
        ),
        migrations.AddField(
            model_name='elaborationssteps',
            name='stir_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calories_tracker.stirtypes'),
        ),
        migrations.AddField(
            model_name='elaborationssteps',
            name='stir_values',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elaborationssteps',
            name='temperatures_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calories_tracker.temperaturestypes'),
        ),
        migrations.AddField(
            model_name='elaborationssteps',
            name='temperatures_values',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
