# Generated by Django 4.1.3 on 2022-12-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0024_remove_steps_stir_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elaborationssteps',
            name='temperature',
        ),
    ]
