# Generated by Django 4.1.3 on 2022-12-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0025_remove_elaborationssteps_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elaborationssteps',
            name='stir',
        ),
    ]
