# Generated by Django 4.1.3 on 2022-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0026_remove_elaborationssteps_stir'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaborationsproductsinthrough',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
