# Generated by Django 4.1.3 on 2022-12-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0027_elaborationsproductsinthrough_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
