# Generated by Django 4.1.3 on 2022-12-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0029_elaborationsproductsinthrough_ni'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaborations',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elaborations',
            name='automatic_adaptation_step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elaborationsproductsinthrough',
            name='automatic_percentage',
            field=models.IntegerField(default=100),
        ),
    ]
