# Generated by Django 4.1.4 on 2022-12-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0033_auto_20221210_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeslinks',
            name='content',
        ),
        migrations.RemoveField(
            model_name='recipeslinks',
            name='mime',
        ),
    ]
