# Generated by Django 4.1.4 on 2022-12-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0034_remove_recipeslinks_content_remove_recipeslinks_mime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
