# Generated by Django 4.1.4 on 2022-12-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0037_historicalbiometrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='can_container',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='can_container_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steps',
            name='can_products_in_step',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='can_stir',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='can_temperatures',
            field=models.BooleanField(default=True),
        ),
    ]
