# Generated by Django 4.1.4 on 2022-12-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0038_steps_can_container_steps_can_container_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='man_container',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='man_container_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steps',
            name='man_products_in_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steps',
            name='man_stir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steps',
            name='man_temperatures',
            field=models.BooleanField(default=False),
        ),
    ]
