# Generated by Django 4.1.4 on 2023-01-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_tracker', '0039_steps_man_container_steps_man_container_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaborations',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
