# Generated by Django 4.2.3 on 2023-07-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calories_tracker", "0040_alter_elaborations_final_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElaborationsTexts",
            fields=[
                (
                    "elaborations",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="elaborations_texts",
                        serialize=False,
                        to="calories_tracker.elaborations",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        db_comment="Recipe text for this elaboration in markdown format",
                        default="",
                    ),
                ),
            ],
            options={
                "db_table": "elaborations_texts",
                "managed": True,
            },
        ),
    ]
