# Generated by Django 4.2.4 on 2023-09-11 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calories_tracker", "0041_elaborationstexts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ElaborationsSteps",
        ),
        migrations.DeleteModel(
            name="Steps",
        ),
        migrations.DeleteModel(
            name="StirTypes",
        ),
        migrations.DeleteModel(
            name="TemperaturesTypes",
        ),
    ]
