# Generated by Django 4.2.5 on 2023-09-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calories_tracker", "0042_delete_elaborationssteps_delete_steps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elaborationsproductsinthrough",
            name="automatic_parent",
            field=models.ForeignKey(
                blank=True,
                db_comment="Parent ElaborationProductsIn for this register",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="calories_tracker.elaborationsproductsinthrough",
            ),
        ),
    ]
