# Generated by Django 4.2.6 on 2023-10-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_tracker", "0043_elaborationsproductsinthrough_automatic_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elaboratedproducts",
            name="recipes",
        ),
        migrations.AddField(
            model_name="elaboratedproducts",
            name="comment",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="elaboratedproducts",
            name="obsolete",
            field=models.BooleanField(default=False),
        ),
    ]
