# Generated by Django 4.2.6 on 2023-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_tracker", "0044_remove_elaboratedproducts_recipes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elaboratedproducts",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
