# Generated by Django 5.2 on 2025-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calories_tracker", "0047_pillevents"),
    ]

    operations = [
        migrations.AddField(
            model_name="pillevents",
            name="highlite_late",
            field=models.BooleanField(
                db_comment="Highlite pill was taken late", default=False
            ),
        ),
    ]
