from django.utils.translation import gettext_lazy as _
_('Extra active')
_('Gain weight')
_('High')
_('Lightly active')
_('Lose weight')
_('Low')
_('Mantain weight')
_('Medium')
_('Moderately active')
_('No risk')
_('Not evaluated')
_('Sedentary')
_('Very active')
