from django.utils.translation import gettext_lazy as _
_('Alcohol-free beer')
_('Alcoholic drinks')
_('Apple')
_('Apricot')
_('Asian rice')
_('Bacon')
_('Bag')
_('Baked potato')
_('Bakery')
_('Banana')
_('Bar')
_('Big')
_('Blueberries')
_('Boiled egg')
_('Bonito')
_('Bottle')
_('Bourbon')
_('Bread and cereals')
_('Bread')
_('Butter')
_('Can')
_('Carrot')
_('Cauliflower')
_('Cherimoya')
_('Chestnuts')
_('Chicken')
_('Chicken. Raw')
_('Chips')
_('Churros')
_('Cola Cao Original')
_('Constantly stir')
_('Cook on medium heat')
_('Cook over high heat')
_('Cook over low heat')
_('Cookie')
_('Croissant')
_('Cup')
_('Dairy products')
_('Diet drinks')
_('Do not remove')
_('Document file')
_('Drained can')
_('Dry nuts')
_('Duck foie grass mousse')
_('Eggs')
_('Eggs')
_('Eggs')
_('Extra active')
_('Extra virgin olive oil')
_('Fish')
_('Fried eggs')
_('Fried peanuts')
_('Fruit')
_('Gain weight')
_('Garlic')
_('Gin')
_('Goat cheese')
_('Grams')
_('Grape')
_('Green asparagus')
_('Green pepper')
_('Ham croquettes')
_('Ham')
_('High')
_('Homemade food')
_('Honey')
_('Huevos de codorniz')
_('Ice cream')
_('In Celsius degrees')
_('Jam')
_('Kiwi')
_('Lambrusco wine')
_('Laurel')
_('Leek')
_('Legumes')
_('Legumes')
_('Lentils')
_('Lightly active')
_('Little stick')
_('Lose weight')
_('Low')
_('Mango')
_('Mantain weight')
_('Mascarpone cheese')
_('Mayonnaise')
_('Meat')
_('Meat')
_('Medium')
_('Medium')
_('Menestra de verduras')
_('Milliliter')
_('Minced meat')
_('Moderately active')
_('Mushrooms (Fungi)')
_('Mushrooms')
_('Nectarine')
_('No risk')
_('Not evaluated')
_('Octopus')
_('Oils and fats')
_('Onion')
_('Orange')
_('Package')
_('Palmera de chocolate')
_('Panceta sin corteza')
_('Panettone')
_('Peach')
_('Pear')
_('Peppers from Padrón')
_('Persimmon')
_('Photo file')
_('Pig')
_('Pill')
_('Pineapple')
_('Plantain')
_('Pork ribs')
_('Potatos')
_('Prawns')
_('Processed foods')
_('Pumpkin')
_('REUSEME')
_('REUSEME')
_('REUSEME')
_('REUSEME')
_('Rice')
_('Risotto')
_('Roast lamb')
_('Room temperature')
_('Rum')
_('Salt')
_('Salty bakery')
_('Sandwich loaf')
_('Saturn peach')
_('Sedentary')
_('Sesame')
_('Slice')
_('Soup Rice')
_('Soups and creams')
_('Soups and infusions')
_('Spanish omelette')
_('Spices')
_('Stir every 5 minutes')
_('Strawberries')
_('Strawberry jam')
_('Sugar')
_('Sugary drinks')
_('Sunflower oil')
_('Sweet bakery')
_('Sweet corn')
_('Sweets')
_('Tablespoon')
_('Tangerines')
_('Teaspoon')
_('Thermomix velocity')
_('Thick Crust Pizza with cheese')
_('Toast')
_('Tray')
_('Uncooked potato')
_('Uncooked rice')
_('Unit')
_('Vacuum container')
_('Vegetables')
_('Vegetables')
_('Very active')
_('Video file')
_('Video link')
_('Water')
_('Water')
_('Watermelon')
_('Web page file')
_('Web page link')
_('White bread')
_('White wine')
_('Whole milk')
_('Zucchini')
