from django.utils.translation import gettext_lazy as _
_('Alcoholic drinks')
_('Bag (100g)')
_('Bag (200g)')
_('Bag (250g)')
_('Bag (600g)')
_('Bag (65g)')
_('Bar (20g)')
_('Bottle (500g)')
_('Bread and cereals')
_('Can (275g)')
_('Can (330g)')
_('Can (40g)')
_('Can (425g)')
_('Can (560g)')
_('Can (73g)')
_('Can (75g)')
_('Can (80g)')
_('Cookie (17g)')
_('Dairy products')
_('Diet drinks')
_('Dry nuts')
_('Eggs')
_('Extra active')
_('Fish')
_('Fruit')
_('Gain weight')
_('High')
_('Homemade food')
_('Legumes')
_('Lightly active')
_('Lose weight')
_('Low')
_('Mantain weight')
_('Meat')
_('Medium')
_('Moderately active')
_('No risk')
_('Not evaluated')
_('Oils and fats')
_('Processed foods')
_('Scrambled eggs')
_('Sedentary')
_('Soups and infusions')
_('Spices')
_('Sugary drinks')
_('Sweets')
_('Vegetables')
_('Very active')
_('Water')
_('Wholemeal bread')
