# Generated by Django 4.0.3 on 2022-04-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formats',
            name='last',
        ),
    ]
