# Generated by Django 4.0.3 on 2022-04-11 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_systemproducts_formats_alter_formats_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemproducts',
            name='version',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='version_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='version_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogs.systemproducts'),
        ),
    ]
