# Generated by Django 4.0.3 on 2022-04-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_systemproducts_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formats',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='additives',
            field=models.ManyToManyField(blank=True, to='catalogs.additives'),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='calcium',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='calories',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='cholesterol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='ferrum',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='formats',
            field=models.ManyToManyField(blank=True, to='catalogs.formats'),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='magnesium',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='phosphor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='salt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='saturated_fat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemproducts',
            name='system_companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogs.systemcompanies'),
        ),
    ]
