# Generated by Django 4.0.3 on 2022-04-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_alter_formats_amount_alter_systemproducts_additives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formats',
            name='amount',
        ),
        migrations.AlterField(
            model_name='formats',
            name='name',
            field=models.TextField(),
        ),
    ]
