# Generated by Django 4.0.3 on 2022-04-12 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_remove_systemproducts_formats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProductsFormatsThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('formats', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogs.formats')),
            ],
        ),
        migrations.AddField(
            model_name='systemproducts',
            name='formats',
            field=models.ManyToManyField(blank=True, through='catalogs.SystemProductsFormatsThrough', to='catalogs.formats'),
        ),
        migrations.AddField(
            model_name='systemproductsformatsthrough',
            name='system_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogs.systemproducts'),
        ),
    ]
